version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "movie_notebook_backend/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd movie_notebook_backend && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "movie_notebook_backend/pom.xml" }}

      # run tests!
      - run: cd movie_notebook_backend && ./mvnw clean integration-test 

      - store_test_results:
          path: movie_notebook_backend/target/surefire-reports

      - run:
          name: Send report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)