export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const SAVE_MOVIE = 'SAVE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SELECT_FOUND_MOVIE = 'SELECT_FOUND_MOVIE';
export const TYPPING_TIMEOUT = 'TYPPING_TIMEOUT';

export const SELECT_PAGE = 'SELECT_PAGE';

export const REQUEST = 'REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
